name: Deploy Angular App to VPS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  setup-and-build:
    uses: ./.github/workflows/pnpm.yml  # Calls reusable workflow

  deploy:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Angular CLI
        run: pnpm add -g @angular/cli

      - name: Build Angular app
        run: pnpm exec ng build --configuration=production

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete-before
          path: dist/
          remote_path: /var/www/portfolio-ssr
          remote_host: ${{ secrets.VPS_IP }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
