name: Deploy Angular App to VPS

on:
  push:
    branches:
      - main   # Only trigger on push to the main branch
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.editorconfig'

jobs:
  install-pnpm:
    uses: ./.github/workflows/pnpm.yml

  deps-build-deploy:
    needs: install-pnpm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Angular app
        run: ng build --configuration=production

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete-before
          path: dist/
          remote_path: /var/www/portfolio-ssr
          remote_host: ${{ secrets.VPS_IP }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_KEY }}