name: Lint Check

on:
  pull_request:
    paths:
      - 'src/**'
      - '*.js'
    types: [opened, synchronize, reopened, closed]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src/ --ignore-pattern '**/*.spec.ts' || true

      - name: Post ESLint result as PR comment
        if: ${{ failure() }}
        run: |
          ESLINT_OUTPUT=$(npx eslint src/ --ignore-pattern '**/*.spec.ts' --ext .js,.ts --format json)
          if [[ -n "$ESLINT_OUTPUT" ]]; then
            PR_COMMENT="### ESLint Results\n\n\`\`\`json\n$ESLINT_OUTPUT\n\`\`\`"
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -X POST \
                 -d "{\"body\": \"$PR_COMMENT\"}" \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
          fi
