name: ESLint Check

on:
  pull_request_target:
    paths:
      - 'src/**'
      - '*.js'
    types: [opened, synchronize, reopened, closed] # -> only with pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint:json
        continue-on-error: true

      - uses: ldiego73/eslint-report-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report: reports/lint.json