name: ESLint Check

on:
  pull_request:
    paths:
      - 'src/**'
      - '*.js'
    types: [opened, synchronize, reopened, closed]

jobs:
  install-pnpm:
    uses: ./.github/workflows/pnpm.yml

  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm ci

      - name: Run ESLint
        run: pnpm run lint:json
        continue-on-error: true

      - uses: ldiego73/eslint-report-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report: reports/lint.json