name: Try to build Angular app

on:
  pull_request:
    paths:
      - 'src/**'
      - '*.js'
    types: [opened, synchronize, reopened, closed]

jobs:
  install-pnpm:
    uses: ./.github/workflows/pnpm.yml

  try-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Install Angular CLI
        run: pnpm install -g @angular/cli

      - name: Build Angular app
        run: ng build --configuration=production